name: Pages

on:
  push:
    branches:
      - main  # Cabang default tempat Hexo Anda berada

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 1. Checkout kode sumber
      - uses: actions/checkout@v3
        with:
          submodules: recursive  # Sinkronisasi submodule (jika ada)

      # 2. Setup Node.js versi stabil yang kompatibel
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Hexo kompatibel dengan Node.js 16

      # 3. Cache dependencies untuk mempercepat proses
      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      # 4. Instal dependensi Hexo
      - name: Install dependencies
        run: npm install

      # 5. Generate file statis Hexo
      - name: Build Hexo
        run: npm run build # Jika ada error, ubah menjadi `hexo generate`

      # 6. Deploy ke GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
